Use anyhow crate for error handling
To simplify error handling we can utilize the `anyhow` crate:
https://github.com/dtolnay/anyhow

This means we can add an error context and reduce the type overhead in
function signatures. It also formats the errors in a more sane way, for
example if build.rs would fail:

```
  Error: compile CRI protocol buffers

  Caused by:
      No such file or directory (os error 2)
```

Signed-off-by: Sascha Grunert <sgrunert@suse.com>